export const START_QUESTIONS_FETCHING = 'START_QUESTIONS_FETCHING';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';

export const QUESTION_ANSWERED = 'QUESTION_ANSWERED';
